### ISSUE TITLE
[NON-ISSUE] Thanks!

### ISSUE THREAD

**Issue by dumbasPL** [es3n1n/no-defender#1]
I had the same idea a few years ago but never got around to implementing it, thanks. I wonder if this could be done without using a signed binary but my guess is a solid no because M$ is M$.

**Comment by es3n1n** [comment]
Yeah, I reverse-engineered this API a bit, and it seemed like there's no way to register your stuff in WSC without having at least a signed binary and some other stuff. Although I didn't look much into it so I might be missing something there.

**Comment by szdytom** [comment]
Coolest project I've ever seen this year! Wish I could be have the skill one day.
