### ISSUE TITLE
unable to open wsc_proxy

### ISSUE THREAD

**Issue by HongYue1** [es3n1n/no-defender#2]
Using cmd as admin I get this error:

```
C:\Users\username\Documents\Release>no-defender-loader.exe --disable
** saving the ctx..
** setting the registry keys up
** removing the service
unable to open wsc_proxy
```
OS: Windows 11 23H2(22631.3447)
Antivirus: ESET internet security (if it matters)

**Comment by es3n1n** [comment]
Hey, can you please check out this release https://github.com/es3n1n/no-defender/releases/tag/v1.0.1 ?
But since v1.0.0 broke some stuff, please start the loader without `--disable` the first time, then start it again with `--disable`, which should disable everything.

**Comment by HongYue1** [comment]
> Hey, can you please check out this release [`v1.0.1` (release)](https://github.com/es3n1n/no-defender/releases/tag/v1.0.1) ? But since v1.0.0 broke some stuff, please start the loader without `--disable` the first time, then start it again with `--disable`, which should disable everything.

Working fine now, Thanks!

![image](https://github.com/es3n1n/no-defender/assets/87040288/7c740674-6611-4bf5-bd67-c5f999fa5606)
