### ISSUE TITLE
Is a 32-bit x86 version possible?

### ISSUE THREAD

**Issue by jknockel** [es3n1n/no-defender#3]
I suppose this would depend on whether there are 32-bit versions of `wsc.dll` and `wsc_proxy.exe` floating around.

**Comment by es3n1n** [comment]
Hello, I don't think avast is shipping 32-bit versions of their modules (at least I don't have them) so the answer is no, this is not possible as of now. Besides, why would you need a 32-bit version if you don't mind me asking?

**Comment by jknockel** [comment]
My use case is for virtual machines where 32-bit Windows takes up less RAM and disk space.

**Comment by jknockel** [comment]
Would these be helpful?  I grabbed them from an Avast install to a 32-bit Windows VM.  I believe they are the 32-bit equivalents of `wsc.dll` and `wsc_proxy.exe`.

[avast-bin-32bit.zip](https://github.com/es3n1n/no-defender/files/15439962/avast-bin-32bit.zip)

**Comment by es3n1n** [comment]
Oh, how interesting. I will take a look at it in a couple of hours, thank you.

**Comment by bb010g** [comment]
Per <https://infosec.exchange/@bontchev/112496482944845316>, the Avast drivers shouldn't be necessary on 64-bit or 32-bit.

**Comment by es3n1n** [comment]
Added x86 builds in https://github.com/es3n1n/no-defender/releases/tag/v1.1.0
