### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by emv33** [es3n1n/no-defender#4]
I have installed this, but MsMpEng.exe keeps running and reading files all day, including all executables I run, and creating cache files in C:\ProgramData\Microsoft\Windows Defender\Scans\

![image](https://github.com/es3n1n/no-defender/assets/142946271/81de976d-cc76-4dbc-a6fd-3e820e1b8733)

This is Windows 11 24H2

**Comment by creopard** [comment]
Did you also uncheck the setting sitting right below your screenshot?

![defender](https://github.com/es3n1n/no-defender/assets/14175483/12f36d7d-ad3f-4224-908b-02b64bf57175)

**Comment by emv33** [comment]
It was disabled already.

Besides, this isn't a periodic check for threats. It's realtime scanning.

**Comment by emv33** [comment]
Found the reason for this: Smart App Control was in evaluation mode (this is the default).

https://support.microsoft.com/en-gb/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003
