### ISSUE TITLE
Suppress Firewall warning aswell

### ISSUE THREAD

**Issue by Jusix** [es3n1n/no-defender#5]
Hello,

as the title already states. Would it be possible to extend your tool to also suppress the Windows Firewall disabled warnings messages?

Thanks
Jusix

**Comment by es3n1n** [comment]
Hello, yes, I think this might be possible but I would have to double-check. I am very bad at estimating the time so no ETA, but it made me curious and I will probably try to do this later on this week.

**Comment by es3n1n** [comment]
Added in https://github.com/es3n1n/no-defender/releases/tag/v1.1.0

**Comment by Jusix** [comment]
Phenomenal work, thank you very much!
